### ISSUE TITLE
Appboy bundle key error while uploading app compiled on xcode 7

### ISSUE THREAD

**Issue by rohitv82** [Appboy/appboy-ios-sdk#35]
2015-09-30 15:33:54 EDT] <main> ERROR: ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/myapp.app/Appboy.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the component.

**Comment by Wenzhi** [comment]
Hi @rohitv82, 

The issue you mentioned is fixed from SDK version 2.14.0. You can fix it by upgrading your Appboy SDK. We highly recommend you to use the latest version of SDK, which is 2.16.0 right now.

Please let us know if you have any other questions.

Thanks,

**Comment by rohitv82** [comment]
Hi There

Sorry  for not informing you earlier, i am using Appboy Xamarin Component version 1.1 which is latest version. And i am still facing this issue.

**Comment by briancaw** [comment]
Hi @rohitv82 

Our Appboy Xamarin Component is not currently integrated with the latest Appboy iOS SDK.  We'll be updating in the near future, likely early next week.  We'll add updates on release timing to this issue as they become available.

Please let us know if you have any other comments or questions.

Thanks,
Brian

**Comment by briancaw** [comment]
Hi @rohitv82 

We have updated our Xamarin binding to use our most recent iOS SDK (version 2.17.1), which should fix this issue.  Please reopen this ticket if you're still having any issues. 

Thanks,
Brian
